namespace PL0Resources
{
    public enum Token
    {
        NUL_SYM = 1, IDENT_SYM, NUMBER_SYM, PLUS_SYM,
        MINUS_SYM, MULT_SYM, SLASH_SYM, ODD_SYM,
        EQL_SYM, NEQ_SYM, LES_SYM, LEQ_SYM,
        GTR_SYM, GEQ_SYM, LPARENT_SYM, RPARENT_SYM,
        COMMA_SYM, SEMICOLON_SYM, PERIOD_SYM, BECOMES_SYM,
        BEGIN_SYM, END_SYM, IF_SYM, THEN_SYM,
        WHILE_SYM, DO_SYM, CALL_SYM, CONST_SYM,
        VAR_SYM, PROC_SYM, WRITE_SYM, READ_SYM, ELSE_SYM,
        STRING_SYM
    }
}
